---
title: "Gapminder Exercise Template"
author: "Ezinne Nwankwo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 7)
```


## Load packages

```{r message=FALSE}
library(tidyverse)
```

```{r}
x=2
x*3
```

## Load data

```{r}
gap <- read_csv("https://bit.ly/gap_data")
```

## Exercises

### Exercise 1

How many observations are in this dataset?

```{r nrow}

num_rows <- nrow(gap)

```
There are 'r num_rows' observations in the dataset or there are 'r nrow(gap)' observations in the dataset. 
### Exercise 2

Visualize the relationship between GDP and life expectancy for 
countries in Europe in 1952 using a scatter plot.


```{r eu_52}

eu_52 = gap[which(gap$continent == 'Europe' & gap$year== '1952'),] 

ggplot(data = eu_52, aes(x = gdpPercap, y = lifeExp))+ 
  geom_point()


```

### Exercise 3

Add year 1967 in another color.

```{r eu_52_67}

eu_5267 = gap[which(gap$continent == 'Europe' & gap$year == c(1952,1967)), ]

ggplot(data = eu_5267, aes (x = gdpPercap , y = lifeExp, color = factor(year))) + 
  geom_point()

```

